(ns clj-grpc.codec
  "DEPRECATED alias for clj-protobuf.codec.

  Code generated by protoc-gen-clojure <= 0.3.x requires this namespace; from
  0.4.0 the default is clj-protobuf.codec. Shipped by the clj-protobuf artifact
  — deliberately, so message-only files keep working without any gRPC artifact
  on the classpath. The clj-grpc artifact must never define this namespace, or
  the two artifacts collide. Removed at 1.0."
  {:deprecated "0.1.5"}
  (:require [clj-protobuf.codec :as codec]))

(def ^{:deprecated "0.1.5"} set-field! codec/set-field!)
(def ^{:deprecated "0.1.5"} get-field codec/get-field)
