(ns clj-grpc.runtime
  "DEPRECATED alias for clj-protobuf.runtime.

  Code generated by protoc-gen-clojure <= 0.3.x requires this namespace; from
  0.4.0 the default is clj-protobuf.runtime. Shipped by the clj-protobuf
  artifact — deliberately, so message-only files keep working without any gRPC
  artifact on the classpath. The clj-grpc artifact must never define this
  namespace, or the two artifacts collide. Removed at 1.0."
  {:deprecated "0.1.5"}
  (:require [clj-protobuf.runtime :as rt]))

(def ^{:deprecated "0.1.5"} file-descriptor rt/file-descriptor)
(def ^{:deprecated "0.1.5"} known-file rt/known-file)
(def ^{:deprecated "0.1.5"} message rt/message)
(def ^{:deprecated "0.1.5"} field rt/field)
