;; Generated by protoc-gen-clojure from fixtures/wire/e2024.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.wire.e2024
  (:require [clj-protobuf.codec :as codec]
            [clj-protobuf.runtime :as rt]))

(def ^:private descriptor-b64
  "ChlmaXh0dXJlcy93aXJlL2UyMDI0LnByb3RvEhNmaXh0dXJlcy53aXJlLmUyMDI0IhYKBExlYWYSDgoCaWQYASABKAlSAmlkItkDCgRXaXJlEhAKA3N0chgBIAEoCVIDc3RyEh8KB2NoZWNrZWQYAiABKAlCBaoBAiACUgdjaGVja2VkEiEKCGV4cGFuZGVkGAMgAygFQgWqAQIYAlIIZXhwYW5kZWQSFgoGcGFja2VkGAQgAygFUgZwYWNrZWQSPgoJZGVsaW1pdGVkGAUgASgLMhkuZml4dHVyZXMud2lyZS5lMjAyNC5MZWFmQgWqAQIoAlIJZGVsaW1pdGVkEkIKD2xlbmd0aF9wcmVmaXhlZBgGIAEoCzIZLmZpeHR1cmVzLndpcmUuZTIwMjQuTGVhZlIObGVuZ3RoUHJlZml4ZWQSIQoIaW1wbGljaXQYByABKAVCBaoBAggCUghpbXBsaWNpdBIaCghleHBsaWNpdBgIIAEoBVIIZXhwbGljaXQSLQoEb3BlbhgJIAEoDjIZLmZpeHR1cmVzLndpcmUuZTIwMjQuT3BlblIEb3BlbhIzCgZjbG9zZWQYCiABKA4yGy5maXh0dXJlcy53aXJlLmUyMDI0LkNsb3NlZFIGY2xvc2VkEjwKC2Nsb3NlZF9saXN0GAsgAygOMhsuZml4dHVyZXMud2lyZS5lMjAyNC5DbG9zZWRSCmNsb3NlZExpc3QqKAoET3BlbhIUChBPUEVOX1VOU1BFQ0lGSUVEEAASCgoGT1BFTl9BEAEqKgoGQ2xvc2VkEgwKCENMT1NFRF9BEAESDAoIQ0xPU0VEX0IQAhoEOgIQAkIjChxjb20uYWNtZS5maXh0dXJlcy53aXJlLmUyMDI0kgMCIANiCGVkaXRpb25zcOkH")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
(declare proto->Leaf--slot-map)
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Leaf [id])
(def Leaf-prototype (rt/message file-descriptor "Leaf" "com.acme.fixtures.wire.e2024.Leaf"))
(def ^:private Leaf--id (rt/field Leaf-prototype "id"))
(defn Leaf->proto
  "Clojure -> protobuf. Takes the Leaf record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Leaf->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Leaf-prototype)]
     (codec/set-field! b Leaf--id (:id m) opts)
     (.build b))))
(defn proto->Leaf
  "protobuf -> a Leaf record. Absent fields are nil."
  ([msg] (proto->Leaf msg nil))
  ([^com.google.protobuf.Message msg opts]
   (if (and (nil? opts) (rt/compiled-message? msg))
     (->Leaf
      (rt/slot msg 0)
      )
     (->Leaf
      (codec/get-field msg Leaf--id opts)
      ))))
(defn- proto->Leaf--slot-map
  "Leaf as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  (let [id--v (rt/slot msg 0)]
    (if (some? id--v)
      {:id id--v}
      {})))

(defrecord Wire [str checked expanded packed delimited length-prefixed implicit explicit open closed closed-list])
(def Wire-prototype (rt/message file-descriptor "Wire" "com.acme.fixtures.wire.e2024.Wire"))
(def ^:private Wire--str (rt/field Wire-prototype "str"))
(def ^:private Wire--checked (rt/field Wire-prototype "checked"))
(def ^:private Wire--expanded (rt/field Wire-prototype "expanded"))
(def ^:private Wire--packed (rt/field Wire-prototype "packed"))
(def ^:private Wire--delimited (rt/field Wire-prototype "delimited"))
(def ^:private Wire--length-prefixed (rt/field Wire-prototype "length_prefixed"))
(def ^:private Wire--implicit (rt/field Wire-prototype "implicit"))
(def ^:private Wire--explicit (rt/field Wire-prototype "explicit"))
(def ^:private Wire--open (rt/field Wire-prototype "open"))
(def ^:private Wire--closed (rt/field Wire-prototype "closed"))
(def ^:private Wire--closed-list (rt/field Wire-prototype "closed_list"))
(defn Wire->proto
  "Clojure -> protobuf. Takes the Wire record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Wire->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Wire-prototype)]
     (codec/set-field! b Wire--str (:str m) opts)
     (codec/set-field! b Wire--checked (:checked m) opts)
     (codec/set-field! b Wire--expanded (:expanded m) opts)
     (codec/set-field! b Wire--packed (:packed m) opts)
     (codec/set-field! b Wire--delimited (:delimited m) opts)
     (codec/set-field! b Wire--length-prefixed (:length-prefixed m) opts)
     (codec/set-field! b Wire--implicit (:implicit m) opts)
     (codec/set-field! b Wire--explicit (:explicit m) opts)
     (codec/set-field! b Wire--open (:open m) opts)
     (codec/set-field! b Wire--closed (:closed m) opts)
     (codec/set-field! b Wire--closed-list (:closed-list m) opts)
     (.build b))))
(defn proto->Wire
  "protobuf -> a Wire record. Absent fields are nil."
  ([msg] (proto->Wire msg nil))
  ([^com.google.protobuf.Message msg opts]
   (if (and (nil? opts) (rt/compiled-message? msg))
     (->Wire
      (rt/slot msg 0)
      (rt/slot msg 1)
      (let [^java.util.List l (rt/slot msg 2)] (when (and l (pos? (.size l))) (vec l)))
      (let [^java.util.List l (rt/slot msg 3)] (when (and l (pos? (.size l))) (vec l)))
      (when-some [v (rt/slot msg 4)] (proto->Leaf--slot-map v))
      (when-some [v (rt/slot msg 5)] (proto->Leaf--slot-map v))
      (let [v (rt/slot msg 6)] (if (nil? v) (int 0) v))
      (rt/slot msg 7)
      (when-some [v (rt/slot msg 8)] (case v 0 :OPEN_UNSPECIFIED 1 :OPEN_A (codec/get-field msg Wire--open nil)))
      (when-some [v (rt/slot msg 9)] (case v 1 :CLOSED_A 2 :CLOSED_B (codec/get-field msg Wire--closed nil)))
      (codec/get-field msg Wire--closed-list nil)
      )
     (->Wire
      (codec/get-field msg Wire--str opts)
      (codec/get-field msg Wire--checked opts)
      (codec/get-field msg Wire--expanded opts)
      (codec/get-field msg Wire--packed opts)
      (codec/get-field msg Wire--delimited opts)
      (codec/get-field msg Wire--length-prefixed opts)
      (codec/get-field msg Wire--implicit opts)
      (codec/get-field msg Wire--explicit opts)
      (codec/get-field msg Wire--open opts)
      (codec/get-field msg Wire--closed opts)
      (codec/get-field msg Wire--closed-list opts)
      ))))
