;; Generated by protoc-gen-clojure from fixtures/wire/p3.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.wire.p3
  (:require [clj-protobuf.codec :as codec]
            [clj-protobuf.runtime :as rt]))

(def ^:private descriptor-b64
  "ChZmaXh0dXJlcy93aXJlL3AzLnByb3RvEhBmaXh0dXJlcy53aXJlLnAzIhYKBExlYWYSDgoCaWQYASABKAlSAmlkIvYICgRXaXJlEhAKA2kzMhgBIAEoBVIDaTMyEhAKA2k2NBgCIAEoA1IDaTY0EhAKA3UzMhgDIAEoDVIDdTMyEhAKA3U2NBgEIAEoBFIDdTY0EhAKA3MzMhgFIAEoEVIDczMyEhAKA3M2NBgGIAEoElIDczY0EhAKA2YzMhgHIAEoB1IDZjMyEhAKA2Y2NBgIIAEoBlIDZjY0EhIKBHNmMzIYCSABKA9SBHNmMzISEgoEc2Y2NBgKIAEoEFIEc2Y2NBIQCgNmbHQYCyABKAJSA2ZsdBIQCgNkYmwYDCABKAFSA2RibBISCgRmbGFnGA0gASgIUgRmbGFnEhAKA3N0chgOIAEoCVIDc3RyEhAKA3JhdxgPIAEoDFIDcmF3EiwKBWNvbG9yGBAgASgOMhYuZml4dHVyZXMud2lyZS5wMy5PcGVuUgVjb2xvchIqCgRsZWFmGBEgASgLMhYuZml4dHVyZXMud2lyZS5wMy5MZWFmUgRsZWFmEhYKBnBhY2tlZBgSIAMoBVIGcGFja2VkEh4KCHVucGFja2VkGBMgAygFQgIQAFIIdW5wYWNrZWQSHQoKcGFja2VkX3M2NBgUIAMoElIJcGFja2VkUzY0Eh0KCnBhY2tlZF9kYmwYFSADKAFSCXBhY2tlZERibBIuCgZjb2xvcnMYFiADKA4yFi5maXh0dXJlcy53aXJlLnAzLk9wZW5SBmNvbG9ycxIuCgZsZWF2ZXMYFyADKAsyFi5maXh0dXJlcy53aXJlLnAzLkxlYWZSBmxlYXZlcxIUCgVuYW1lcxgYIAMoCVIFbmFtZXMSNQoFYnlfaWQYGSADKAsyIC5maXh0dXJlcy53aXJlLnAzLldpcmUuQnlJZEVudHJ5UgRieUlkEj4KCGJ5X2NvbG9yGBogAygLMiMuZml4dHVyZXMud2lyZS5wMy5XaXJlLkJ5Q29sb3JFbnRyeVIHYnlDb2xvchIbCghwaWNrX3N0chgbIAEoCUgAUgdwaWNrU3RyEhsKCHBpY2tfaTY0GBwgASgDSABSB3BpY2tJNjQSNQoJcGlja19sZWFmGB0gASgLMhYuZml4dHVyZXMud2lyZS5wMy5MZWFmSABSCHBpY2tMZWFmEhwKB29wdF9pMzIYHiABKAVIAVIGb3B0STMyiAEBEhwKB29wdF9zdHIYHyABKAlIAlIGb3B0U3RyiAEBEhMKBGhpZ2gY/w8gASgJUgRoaWdoEhYKBGh1Z2UY/////wEgASgFUgRodWdlGk8KCUJ5SWRFbnRyeRIQCgNrZXkYASABKAVSA2tleRIsCgV2YWx1ZRgCIAEoCzIWLmZpeHR1cmVzLndpcmUucDMuTGVhZlIFdmFsdWU6AjgBGlIKDEJ5Q29sb3JFbnRyeRIQCgNrZXkYASABKAlSA2tleRIsCgV2YWx1ZRgCIAEoDjIWLmZpeHR1cmVzLndpcmUucDMuT3BlblIFdmFsdWU6AjgBQgYKBHBpY2tCCgoIX29wdF9pMzJCCgoIX29wdF9zdHIqNAoET3BlbhIUChBPUEVOX1VOU1BFQ0lGSUVEEAASCgoGT1BFTl9BEAESCgoGT1BFTl9CEAJCHQoZY29tLmFjbWUuZml4dHVyZXMud2lyZS5wM1ABYgZwcm90bzM=")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Leaf [id])
(def Leaf-prototype (rt/message file-descriptor "Leaf" "com.acme.fixtures.wire.p3.Leaf"))
(def ^:private Leaf--id (rt/field Leaf-prototype "id"))
(defn Leaf->proto
  "Clojure -> protobuf. Takes the Leaf record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Leaf->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Leaf-prototype)]
     (codec/set-field! b Leaf--id (:id m) opts)
     (.build b))))
(defn proto->Leaf
  "protobuf -> a Leaf record. Absent fields are nil."
  ([msg] (proto->Leaf msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Leaf
    (codec/get-field msg Leaf--id opts)
    )))

(defrecord Wire [i32 i64 u32 u64 s32 s64 f32 f64 sf32 sf64 flt dbl flag str raw color leaf packed unpacked packed-s64 packed-dbl colors leaves names by-id by-color pick-str pick-i64 pick-leaf opt-i32 opt-str high huge])
(def Wire-prototype (rt/message file-descriptor "Wire" "com.acme.fixtures.wire.p3.Wire"))
(def ^:private Wire--i32 (rt/field Wire-prototype "i32"))
(def ^:private Wire--i64 (rt/field Wire-prototype "i64"))
(def ^:private Wire--u32 (rt/field Wire-prototype "u32"))
(def ^:private Wire--u64 (rt/field Wire-prototype "u64"))
(def ^:private Wire--s32 (rt/field Wire-prototype "s32"))
(def ^:private Wire--s64 (rt/field Wire-prototype "s64"))
(def ^:private Wire--f32 (rt/field Wire-prototype "f32"))
(def ^:private Wire--f64 (rt/field Wire-prototype "f64"))
(def ^:private Wire--sf32 (rt/field Wire-prototype "sf32"))
(def ^:private Wire--sf64 (rt/field Wire-prototype "sf64"))
(def ^:private Wire--flt (rt/field Wire-prototype "flt"))
(def ^:private Wire--dbl (rt/field Wire-prototype "dbl"))
(def ^:private Wire--flag (rt/field Wire-prototype "flag"))
(def ^:private Wire--str (rt/field Wire-prototype "str"))
(def ^:private Wire--raw (rt/field Wire-prototype "raw"))
(def ^:private Wire--color (rt/field Wire-prototype "color"))
(def ^:private Wire--leaf (rt/field Wire-prototype "leaf"))
(def ^:private Wire--packed (rt/field Wire-prototype "packed"))
(def ^:private Wire--unpacked (rt/field Wire-prototype "unpacked"))
(def ^:private Wire--packed-s64 (rt/field Wire-prototype "packed_s64"))
(def ^:private Wire--packed-dbl (rt/field Wire-prototype "packed_dbl"))
(def ^:private Wire--colors (rt/field Wire-prototype "colors"))
(def ^:private Wire--leaves (rt/field Wire-prototype "leaves"))
(def ^:private Wire--names (rt/field Wire-prototype "names"))
(def ^:private Wire--by-id (rt/field Wire-prototype "by_id"))
(def ^:private Wire--by-color (rt/field Wire-prototype "by_color"))
(def ^:private Wire--pick-str (rt/field Wire-prototype "pick_str"))
(def ^:private Wire--pick-i64 (rt/field Wire-prototype "pick_i64"))
(def ^:private Wire--pick-leaf (rt/field Wire-prototype "pick_leaf"))
(def ^:private Wire--opt-i32 (rt/field Wire-prototype "opt_i32"))
(def ^:private Wire--opt-str (rt/field Wire-prototype "opt_str"))
(def ^:private Wire--high (rt/field Wire-prototype "high"))
(def ^:private Wire--huge (rt/field Wire-prototype "huge"))
(defn Wire->proto
  "Clojure -> protobuf. Takes the Wire record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Wire->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Wire-prototype)]
     (codec/set-field! b Wire--i32 (:i32 m) opts)
     (codec/set-field! b Wire--i64 (:i64 m) opts)
     (codec/set-field! b Wire--u32 (:u32 m) opts)
     (codec/set-field! b Wire--u64 (:u64 m) opts)
     (codec/set-field! b Wire--s32 (:s32 m) opts)
     (codec/set-field! b Wire--s64 (:s64 m) opts)
     (codec/set-field! b Wire--f32 (:f32 m) opts)
     (codec/set-field! b Wire--f64 (:f64 m) opts)
     (codec/set-field! b Wire--sf32 (:sf32 m) opts)
     (codec/set-field! b Wire--sf64 (:sf64 m) opts)
     (codec/set-field! b Wire--flt (:flt m) opts)
     (codec/set-field! b Wire--dbl (:dbl m) opts)
     (codec/set-field! b Wire--flag (:flag m) opts)
     (codec/set-field! b Wire--str (:str m) opts)
     (codec/set-field! b Wire--raw (:raw m) opts)
     (codec/set-field! b Wire--color (:color m) opts)
     (codec/set-field! b Wire--leaf (:leaf m) opts)
     (codec/set-field! b Wire--packed (:packed m) opts)
     (codec/set-field! b Wire--unpacked (:unpacked m) opts)
     (codec/set-field! b Wire--packed-s64 (:packed-s64 m) opts)
     (codec/set-field! b Wire--packed-dbl (:packed-dbl m) opts)
     (codec/set-field! b Wire--colors (:colors m) opts)
     (codec/set-field! b Wire--leaves (:leaves m) opts)
     (codec/set-field! b Wire--names (:names m) opts)
     (codec/set-field! b Wire--by-id (:by-id m) opts)
     (codec/set-field! b Wire--by-color (:by-color m) opts)
     (codec/set-field! b Wire--pick-str (:pick-str m) opts)
     (codec/set-field! b Wire--pick-i64 (:pick-i64 m) opts)
     (codec/set-field! b Wire--pick-leaf (:pick-leaf m) opts)
     (codec/set-field! b Wire--opt-i32 (:opt-i32 m) opts)
     (codec/set-field! b Wire--opt-str (:opt-str m) opts)
     (codec/set-field! b Wire--high (:high m) opts)
     (codec/set-field! b Wire--huge (:huge m) opts)
     (.build b))))
(defn proto->Wire
  "protobuf -> a Wire record. Absent fields are nil."
  ([msg] (proto->Wire msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Wire
    (codec/get-field msg Wire--i32 opts)
    (codec/get-field msg Wire--i64 opts)
    (codec/get-field msg Wire--u32 opts)
    (codec/get-field msg Wire--u64 opts)
    (codec/get-field msg Wire--s32 opts)
    (codec/get-field msg Wire--s64 opts)
    (codec/get-field msg Wire--f32 opts)
    (codec/get-field msg Wire--f64 opts)
    (codec/get-field msg Wire--sf32 opts)
    (codec/get-field msg Wire--sf64 opts)
    (codec/get-field msg Wire--flt opts)
    (codec/get-field msg Wire--dbl opts)
    (codec/get-field msg Wire--flag opts)
    (codec/get-field msg Wire--str opts)
    (codec/get-field msg Wire--raw opts)
    (codec/get-field msg Wire--color opts)
    (codec/get-field msg Wire--leaf opts)
    (codec/get-field msg Wire--packed opts)
    (codec/get-field msg Wire--unpacked opts)
    (codec/get-field msg Wire--packed-s64 opts)
    (codec/get-field msg Wire--packed-dbl opts)
    (codec/get-field msg Wire--colors opts)
    (codec/get-field msg Wire--leaves opts)
    (codec/get-field msg Wire--names opts)
    (codec/get-field msg Wire--by-id opts)
    (codec/get-field msg Wire--by-color opts)
    (codec/get-field msg Wire--pick-str opts)
    (codec/get-field msg Wire--pick-i64 opts)
    (codec/get-field msg Wire--pick-leaf opts)
    (codec/get-field msg Wire--opt-i32 opts)
    (codec/get-field msg Wire--opt-str opts)
    (codec/get-field msg Wire--high opts)
    (codec/get-field msg Wire--huge opts)
    )))
