(ns build
  "The Clojars path: jar, install, deploy. Deliberately the only place
  tools.build appears — Bazel owns build and test everywhere else, and this
  file reads the same deps.edn and version.edn they do, so there is exactly one
  place a version or dependency is declared.

  Usage:
    clojure -T:build jar
    clojure -T:build install
    clojure -T:build deploy    ; needs CLOJARS_USERNAME / CLOJARS_PASSWORD"
  (:require [clojure.edn :as edn]
            [clojure.tools.build.api :as b]
            [deps-deploy.deps-deploy :as dd]))

(def lib 'com.github.bpalermo/clj-protobuf)
(def version (:version (edn/read-string (slurp "version.edn"))))
(def class-dir "target/classes")
(def jar-file (format "target/%s-%s.jar" (name lib) version))
(def basis (delay (b/create-basis {:project "deps.edn"})))

(defn clean [_] (b/delete {:path "target"}))

(defn jar
  "Source-only jar: Clojure libraries ship sources and compile in the
  consumer's process, so records and protocols specialize against the
  consumer's own dependency versions."
  [_]
  (clean nil)
  (b/write-pom {:class-dir class-dir
                :lib lib
                :version version
                :basis @basis
                :src-dirs ["src"]
                :scm {:url "https://github.com/bpalermo/clj-protobuf"
                      :connection "scm:git:git://github.com/bpalermo/clj-protobuf.git"
                      :developerConnection "scm:git:ssh://git@github.com/bpalermo/clj-protobuf.git"
                      :tag (str "v" version)}
                :pom-data [[:description
                            "Protobuf runtime for code generated by protoc-gen-clojure: records in, protoc's bytes out. Editions through 2024."]
                           [:url "https://github.com/bpalermo/clj-protobuf"]
                           [:licenses
                            [:license
                             [:name "Apache-2.0"]
                             [:url "https://www.apache.org/licenses/LICENSE-2.0"]]]]})
  (b/copy-dir {:src-dirs ["src"] :target-dir class-dir})
  (b/jar {:class-dir class-dir :jar-file jar-file}))

(defn install [_]
  (jar nil)
  (b/install {:basis @basis :lib lib :version version
              :jar-file jar-file :class-dir class-dir}))

(defn deploy [_]
  (jar nil)
  (dd/deploy {:installer :remote
              :artifact (b/resolve-path jar-file)
              :pom-file (b/pom-path {:lib lib :class-dir class-dir})}))
